spring:
  datasource:
      url: jdbc:mysql://localhost:3306/iot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
web:
  faceDir: /Users/xieqingdi/Downloads/face
oa:
  appId: Potc5cAAaXVlQASwU233NraEEo5KXAat
  tenantId: lfdc
  secret: 79246cdd-dfa2-47ad-9252-289b78b8947e